// All 30 SAPI Tier 1 Questions grouped by dimension
const ALL_QUESTIONS = [
  // DIMENSION 1 — COMPUTE CAPACITY
  {
    id: 1,
    dimension: 1,
    dimension_name: "Compute Capacity",
    question_text: "What is your organisation's primary AI compute infrastructure?",
    option_a: "We use public cloud (AWS, Azure, GCP) for all AI workloads",
    option_b: "We use a mix of public cloud and on-premise GPU/TPU hardware",
    option_c: "We operate dedicated on-premise AI compute (GPU clusters, HPC)",
    option_d: "We operate sovereign/air-gapped compute for classified or regulated workloads",
    option_e: "We have no dedicated AI compute infrastructure",
    score_a: 25,
    score_b: 50,
    score_c: 75,
    score_d: 95,
    score_e: 5
  },
  {
    id: 2,
    dimension: 1,
    dimension_name: "Compute Capacity",
    question_text: "What percentage of your AI workloads run on infrastructure located within your nation's borders?",
    option_a: "0–20%",
    option_b: "21–50%",
    option_c: "51–80%",
    option_d: "81–100%",
    option_e: null,
    score_a: 15,
    score_b: 40,
    score_c: 70,
    score_d: 95,
    score_e: null
  },
  {
    id: 3,
    dimension: 1,
    dimension_name: "Compute Capacity",
    question_text: "How resilient is your AI compute to energy disruption?",
    option_a: "No dedicated energy planning for AI workloads",
    option_b: "Standard commercial energy contracts; no AI-specific provision",
    option_c: "Dedicated energy supply agreements for data centre / AI operations",
    option_d: "National grid allocation or renewable energy contracts dedicated to AI",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 4,
    dimension: 1,
    dimension_name: "Compute Capacity",
    question_text: "How exposed is your AI hardware supply chain to foreign dependency?",
    option_a: "100% dependent on foreign-fabricated chips (no domestic supply chain visibility)",
    option_b: "Foreign-fabricated but with diversified suppliers and strategic stockpiles",
    option_c: "Some domestic assembly or packaging; fabrication remains foreign",
    option_d: "Partial domestic fabrication capability or strategic alliance with fabricator",
    option_e: "Sovereign fabrication or guaranteed allied-nation supply agreement",
    score_a: 10,
    score_b: 30,
    score_c: 50,
    score_d: 75,
    score_e: 95
  },
  {
    id: 5,
    dimension: 1,
    dimension_name: "Compute Capacity",
    question_text: "What is your total installed data centre capacity dedicated to or available for AI workloads?",
    option_a: "No dedicated data centre capacity",
    option_b: "< 10 MW total capacity",
    option_c: "10–50 MW",
    option_d: "50–200 MW",
    option_e: "> 200 MW",
    score_a: 5,
    score_b: 25,
    score_c: 50,
    score_d: 75,
    score_e: 95
  },
  // DIMENSION 2 — CAPITAL FORMATION
  {
    id: 6,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "What proportion of your government's total R&D budget is allocated to AI infrastructure and development?",
    option_a: "No dedicated AI budget line",
    option_b: "< 1% of total R&D spend",
    option_c: "1–3% of total R&D spend",
    option_d: "3–5% of total R&D spend",
    option_e: "> 5% of total R&D spend",
    score_a: 5,
    score_b: 20,
    score_c: 45,
    score_d: 70,
    score_e: 95
  },
  {
    id: 7,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "Does your nation have sovereign wealth fund or state-backed investment vehicles with explicit AI infrastructure mandates?",
    option_a: "No SWF or state-backed AI fund exists",
    option_b: "SWF exists but with no AI-specific allocation",
    option_c: "SWF exists with general technology allocation that includes AI",
    option_d: "SWF has an explicit, published AI infrastructure allocation",
    option_e: null,
    score_a: 5,
    score_b: 25,
    score_c: 55,
    score_d: 90,
    score_e: null
  },
  {
    id: 8,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "How would you characterise the AI venture capital ecosystem in your country?",
    option_a: "Minimal AI VC activity",
    option_b: "Some AI VC deals but fragmented and below $500M total annually",
    option_c: "Active AI VC ecosystem with $500M–$5B annually",
    option_d: "Deep AI VC market with > $5B annually and domestic institutional LPs",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 95,
    score_e: null
  },
  {
    id: 9,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "Do your national development finance institutions (DFIs) have AI infrastructure financing capability?",
    option_a: "No DFI involvement in AI financing",
    option_b: "DFI finances general technology but not AI-specific infrastructure",
    option_c: "DFI has financed AI-adjacent infrastructure in the past 3 years",
    option_d: "DFI has a published AI infrastructure mandate with active pipeline",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 60,
    score_d: 90,
    score_e: null
  },
  {
    id: 10,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "What is the typical timeframe from government AI budget commitment to operational infrastructure delivery?",
    option_a: "> 36 months or unknown",
    option_b: "24–36 months",
    option_c: "12–24 months",
    option_d: "< 12 months",
    option_e: null,
    score_a: 15,
    score_b: 40,
    score_c: 70,
    score_d: 95,
    score_e: null
  },
  {
    id: 11,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "Does your government have committed multi-year (5–10 year) AI infrastructure funding beyond annual budget cycles?",
    option_a: "No multi-year AI funding commitment exists",
    option_b: "Multi-year commitment exists in strategy documents but no legislative backing",
    option_c: "Legislative or cabinet-level commitment to 3–5 year AI funding",
    option_d: "5–10 year committed AI infrastructure funding with legislative backing",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 60,
    score_d: 95,
    score_e: null
  },
  // DIMENSION 3 — REGULATORY READINESS
  {
    id: 12,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "Does your nation have a formal, published national AI strategy?",
    option_a: "No formal AI strategy",
    option_b: "AI strategy published but with no measurable objectives or timelines",
    option_c: "AI strategy published with objectives, timelines, and institutional ownership",
    option_d: "AI strategy published, implemented, with public progress reporting",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 60,
    score_d: 90,
    score_e: null
  },
  {
    id: 13,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "How clear is the legal framework for AI deployment in your jurisdiction?",
    option_a: "No AI-specific legislation or liability frameworks exist",
    option_b: "General technology law applies; no AI-specific provisions",
    option_c: "AI-specific legislation enacted covering liability and/or IP rules",
    option_d: "Comprehensive AI legislation with liability, IP, and enforcement mechanisms",
    option_e: null,
    score_a: 10,
    score_b: 30,
    score_c: 60,
    score_d: 90,
    score_e: null
  },
  {
    id: 14,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "Can your national procurement system acquire AI systems efficiently?",
    option_a: "AI procurement follows standard IT procurement with no AI-specific provisions",
    option_b: "Some AI procurement guidelines exist but are not widely adopted",
    option_c: "AI-specific procurement frameworks with pre-approved vendor panels",
    option_d: "Rapid AI procurement with sandbox, pilot-to-production, and oversight built in",
    option_e: null,
    score_a: 20,
    score_b: 40,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 15,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "Does your government have an AI ethics governance architecture?",
    option_a: "No AI ethics board or governance structure",
    option_b: "Advisory AI ethics body exists but with no statutory authority",
    option_c: "AI ethics board with statutory authority and published guidelines",
    option_d: "AI ethics governance with mandatory impact assessments and algorithmic audit",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 60,
    score_d: 90,
    score_e: null
  },
  {
    id: 16,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "To what extent does your nation participate in international AI standards bodies?",
    option_a: "No formal participation in AI standards bodies",
    option_b: "Formal membership but limited active participation",
    option_c: "Active working group membership in ISO/IEC JTC 1/SC 42 or equivalent",
    option_d: "Standards leadership: chairing working groups, contributing documents",
    option_e: null,
    score_a: 5,
    score_b: 25,
    score_c: 60,
    score_d: 90,
    score_e: null
  },
  {
    id: 17,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "How coordinated is AI regulation across your government departments?",
    option_a: "Fragmented: departments regulate AI independently with no coordination",
    option_b: "Some coordination exists (working groups, informal channels)",
    option_c: "Formal cross-ministry AI coordination body with published mandate",
    option_d: "Centralised AI governance office with cross-departmental authority",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 18,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "What proportion of your published national AI strategy commitments have been implemented?",
    option_a: "< 10% or no measurable milestones set",
    option_b: "10–30% of commitments have measurable implementation",
    option_c: "31–60% of commitments implemented with evidence",
    option_d: "> 60% of commitments implemented with public reporting",
    option_e: null,
    score_a: 10,
    score_b: 30,
    score_c: 60,
    score_d: 90,
    score_e: null
  },
  // DIMENSION 4 — DATA SOVEREIGNTY
  {
    id: 19,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "Does your nation have enforceable data residency requirements for strategic and citizen data?",
    option_a: "No data localisation requirements",
    option_b: "Data localisation laws exist but enforcement is limited",
    option_c: "Data localisation with enforcement for strategic/government data",
    option_d: "Comprehensive data residency framework with enforcement across public and private sectors",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 20,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "What proportion of government cloud workloads run on sovereign or sovereignty-graded infrastructure?",
    option_a: "Most government cloud workloads on commercial foreign cloud",
    option_b: "Some workloads on sovereign-graded cloud but majority on foreign",
    option_c: "Majority of government cloud on sovereign/domestic infrastructure",
    option_d: "All sensitive government workloads on sovereign cloud with air-gap capability",
    option_e: null,
    score_a: 15,
    score_b: 40,
    score_c: 70,
    score_d: 95,
    score_e: null
  },
  {
    id: 21,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "How does your nation govern cross-border data transfers?",
    option_a: "No specific cross-border data transfer regulations",
    option_b: "GDPR adequacy or bilateral agreement framework in place",
    option_c: "Active cross-border data flow controls with enforcement for government data",
    option_d: "Comprehensive framework: adequacy decisions, contractual clauses, and technical controls",
    option_e: null,
    score_a: 10,
    score_b: 40,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 22,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "Does your nation have classified or air-gapped computing environments for strategic AI workloads?",
    option_a: "No classified or air-gapped AI environments exist",
    option_b: "Classified environments exist but not configured for AI workloads",
    option_c: "Classified AI-ready environments with sovereign cloud regions",
    option_d: "Full trusted operating environment with jurisdictional guarantees and AI integration",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 23,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "How mature is your government's data governance capability?",
    option_a: "No formal data catalogue or quality management across government",
    option_b: "Some departments have data governance; no whole-of-government framework",
    option_c: "Whole-of-government data strategy with cataloguing and access controls",
    option_d: "Mature data governance: real-time cataloguing, quality management, stewardship roles",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 24,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "Are AI models deployed in your country trained on or fine-tuned with domestically controlled data?",
    option_a: "Models are primarily pre-trained foreign models with no domestic fine-tuning",
    option_b: "Some domestic fine-tuning but training data largely foreign-sourced",
    option_c: "Significant domestic training data under sovereign control for key use cases",
    option_d: "Sovereign AI training pipeline: domestic data collection, curation, and model training",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 95,
    score_e: null
  },
  // DIMENSION 5 — DIRECTED INTELLIGENCE MATURITY
  {
    id: 25,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "To what extent are national AI deployments tied to explicit sovereign priorities?",
    option_a: "AI deployments are opportunistic with no link to national strategy",
    option_b: "Some AI projects reference national priorities but most are ad hoc",
    option_c: "AI deployments are systematically mapped to sovereign priority areas",
    option_d: "Mission-first AI: sovereign priorities drive technology selection, not the reverse",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 26,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "What percentage of your national AI initiatives have progressed beyond pilot stage to production deployment?",
    option_a: "< 5% or unknown",
    option_b: "5–15%",
    option_c: "16–30%",
    option_d: "> 30%",
    option_e: null,
    score_a: 10,
    score_b: 30,
    score_c: 60,
    score_d: 90,
    score_e: null
  },
  {
    id: 27,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "How effective is cross-departmental AI coordination in your government?",
    option_a: "No cross-departmental AI coordination exists",
    option_b: "Informal coordination (working groups, shared Slack channels)",
    option_c: "Formal coordination body with published mandate but limited authority",
    option_d: "Systematic cross-government AI coordination with shared infrastructure and budgets",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 55,
    score_d: 90,
    score_e: null
  },
  {
    id: 28,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "Can you attribute specific, documented outcomes to your AI deployments?",
    option_a: "No formal outcome measurement for AI deployments",
    option_b: "Anecdotal outcomes reported but not systematically measured",
    option_c: "Some AI deployments have documented, measured outcomes",
    option_d: "Systematic outcome attribution: all production AI systems have documented, measured impact",
    option_e: null,
    score_a: 5,
    score_b: 25,
    score_c: 55,
    score_d: 90,
    score_e: null
  },
  {
    id: 29,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "Does your government have defined human-agent decision ratios and override mechanisms?",
    option_a: "No human-agent governance framework exists",
    option_b: "General AI ethics principles but no operational human-agent rules",
    option_c: "Human-agent decision policies defined for some departments",
    option_d: "Comprehensive framework: human-agent ratios, override mechanisms, and accountability per department",
    option_e: null,
    score_a: 5,
    score_b: 25,
    score_c: 55,
    score_d: 90,
    score_e: null
  },
  {
    id: 30,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "Have your AI programmes survived at least one leadership change, budget cycle, or political transition?",
    option_a: "AI programmes are too new to have faced a transition",
    option_b: "AI programmes exist but have been disrupted by leadership or budget changes",
    option_c: "Core AI programmes survived one transition with some continuity",
    option_d: "AI programmes have institutional durability: survived multiple transitions with documented continuity",
    option_e: null,
    score_a: 20,
    score_b: 30,
    score_c: 60,
    score_d: 90,
    score_e: null
  },
];

function getAllQuestions() {
  // Group questions by dimension
  const grouped = {};
  
  ALL_QUESTIONS.forEach(q => {
    if (!grouped[q.dimension]) {
      grouped[q.dimension] = {
        dimension_id: q.dimension,
        dimension_name: q.dimension_name,
        questions: []
      };
    }
    grouped[q.dimension].questions.push({
      id: q.id,
      question_text: q.question_text,
      options: [
        { label: 'a', text: q.option_a, score: q.score_a },
        { label: 'b', text: q.option_b, score: q.score_b },
        { label: 'c', text: q.option_c, score: q.score_c },
        { label: 'd', text: q.option_d, score: q.score_d },
        ...(q.option_e ? [{ label: 'e', text: q.option_e, score: q.score_e }] : [])
      ].filter(opt => opt.text !== null)
    });
  });

  return Object.values(grouped);
}

function getQuestionById(id) {
  return ALL_QUESTIONS.find(q => q.id === id);
}

module.exports = {
  getAllQuestions,
  getQuestionById,
  ALL_QUESTIONS
};
