// All 30 SAPI Tier 1 Questions grouped by dimension
const ALL_QUESTIONS = [
  // DIMENSION 1 — COMPUTE CAPACITY
  {
    id: 1,
    dimension: 1,
    dimension_name: "Compute Capacity",
    question_text: "What is your nation's current installed AI training capacity (in petaflops of FP64 equivalent)?",
    option_a: "< 100 petaflops or no disclosed capacity",
    option_b: "100–500 petaflops with published specifications",
    option_c: "500–2,000 petaflops, government or national lab operated",
    option_d: "> 2,000 petaflops, with documented utilisation rates",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 2,
    dimension: 1,
    dimension_name: "Compute Capacity",
    question_text: "Do you have sovereign (domestically controlled) AI training infrastructure?",
    option_a: "No sovereign training capacity; rely entirely on foreign cloud",
    option_b: "Some sovereign capacity, but insufficient for large models",
    option_c: "Sovereign capacity adequate for national priority models",
    option_d: "Extensive sovereign capacity with export controls / foreign access restrictions",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 65,
    score_d: 95,
    score_e: null
  },
  {
    id: 3,
    dimension: 1,
    dimension_name: "Compute Capacity",
    question_text: "What is your current AI inference capacity relative to domestic demand?",
    option_a: "Severe deficit: most inference runs offshore",
    option_b: "Moderate deficit: intermittent capacity constraints",
    option_c: "Adequate: domestic capacity meets current demand",
    option_d: "Surplus: domestic capacity exceeds demand, enabling export",
    option_e: null,
    score_a: 10,
    score_b: 40,
    score_c: 70,
    score_d: 90,
    score_e: null
  },
  {
    id: 4,
    dimension: 1,
    dimension_name: "Compute Capacity",
    question_text: "Is your compute infrastructure integrated with national energy security planning?",
    option_a: "No integration with energy planning",
    option_b: "Ad hoc coordination between AI and energy ministries",
    option_c: "Formal planning documents linking AI compute to energy",
    option_d: "Joint AI-Energy strategic reserve with documented contingencies",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 95,
    score_e: null
  },
  {
    id: 5,
    dimension: 1,
    dimension_name: "Compute Capacity",
    question_text: "Do you have documented plans for sovereign AI compute expansion?",
    option_a: "No documented expansion plans",
    option_b: "Plans exist but lack funding or implementation roadmap",
    option_c: "Funded plan with milestones within 3 years",
    option_d: "Multi-year plan with budget allocation and vendor contracts",
    option_e: null,
    score_a: 5,
    score_b: 25,
    score_c: 60,
    score_d: 95,
    score_e: null
  },
  // DIMENSION 2 — CAPITAL FORMATION
  {
    id: 6,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "Is there a dedicated national AI investment fund or strategic financing mechanism?",
    option_a: "No dedicated AI investment mechanism",
    option_b: "Ad hoc project financing only",
    option_c: "Established AI fund with < $100M AUM",
    option_d: "AI fund > $100M with defined mandate and governance",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 60,
    score_d: 95,
    score_e: null
  },
  {
    id: 7,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "What percentage of national AI investment is domestically sourced (vs foreign capital)?",
    option_a: "< 25% domestic capital",
    option_b: "25–50% domestic capital",
    option_c: "51–75% domestic capital",
    option_d: "> 75% domestic capital or sovereign-only financing",
    option_e: null,
    score_a: 10,
    score_b: 40,
    score_c: 70,
    score_d: 95,
    score_e: null
  },
  {
    id: 8,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "Does your national pension/sovereign wealth fund have a published AI infrastructure allocation?",
    option_a: "No allocation and no plans",
    option_b: "Internal discussions only",
    option_c: "Published strategy but no deployment yet",
    option_d: "Active deployment with disclosed commitments",
    option_e: null,
    score_a: 5,
    score_b: 25,
    score_c: 55,
    score_d: 90,
    score_e: null
  },
  {
    id: 9,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "Are there tax or regulatory incentives for domestic AI infrastructure investment?",
    option_a: "No incentives specific to AI infrastructure",
    option_b: "General R&D tax credits, not AI-specific",
    option_c: "Targeted incentives for AI compute investment",
    option_d: "Comprehensive AI investment framework with multiple incentive types",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 65,
    score_d: 95,
    score_e: null
  },
  {
    id: 10,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "Do public-private AI investment partnerships exist with formal governance?",
    option_a: "No formal partnerships",
    option_b: "Informal collaboration only",
    option_c: "Formal partnerships with limited scale",
    option_d: "Multiple partnerships with disclosed governance and capital commitments",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 60,
    score_d: 95,
    score_e: null
  },
  {
    id: 11,
    dimension: 2,
    dimension_name: "Capital Formation",
    question_text: "Is there a national AI procurement budget with multi-year certainty?",
    option_a: "No specific AI procurement budget",
    option_b: "Annual budget only, subject to yearly renewal",
    option_c: "2-year budget horizon with approved funding",
    option_d: "Multi-year budget (3+ years) with parliamentary/executive approval",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 65,
    score_d: 95,
    score_e: null
  },
  // DIMENSION 3 — REGULATORY READINESS
  {
    id: 12,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "Is there a national AI governance framework with legal force?",
    option_a: "No AI-specific governance framework",
    option_b: "Draft framework or voluntary guidelines only",
    option_c: "Enacted legislation covering some AI applications",
    option_d: "Comprehensive AI statute with regulator and enforcement powers",
    option_e: null,
    score_a: 5,
    score_b: 25,
    score_c: 60,
    score_d: 95,
    score_e: null
  },
  {
    id: 13,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "Has your nation designated a lead AI regulator or oversight body?",
    option_a: "No designated body",
    option_b: "Working group or informal coordination",
    option_c: "Designated lead agency with partial mandate",
    option_d: "Dedicated AI regulator with full licensing and enforcement powers",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 60,
    score_d: 95,
    score_e: null
  },
  {
    id: 14,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "Do you have sector-specific AI regulations (finance, health, defence, transport)?",
    option_a: "No sector-specific requirements",
    option_b: "1 sector with AI-specific rules",
    option_c: "2–3 sectors with tailored regulations",
    option_d: "All critical sectors covered with tailored AI regimes",
    option_e: null,
    score_a: 5,
    score_b: 35,
    score_c: 65,
    score_d: 95,
    score_e: null
  },
  {
    id: 15,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "Are AI risk classifications (e.g., prohibited, high-risk, limited-risk) defined in law?",
    option_a: "No risk classification system",
    option_b: "Informal or draft classification only",
    option_c: "Published classification but not yet legally binding",
    option_d: "Legally binding risk tiers with compliance obligations",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 60,
    score_d: 95,
    score_e: null
  },
  {
    id: 16,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "Does your AI framework include mandatory incident reporting for high-risk systems?",
    option_a: "No incident reporting requirement",
    option_b: "Voluntary reporting only",
    option_c: "Mandatory reporting for public sector AI only",
    option_d: "Mandatory reporting for all high-risk AI, public and private",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 60,
    score_d: 95,
    score_e: null
  },
  {
    id: 17,
    dimension: 3,
    dimension_name: "Regulatory Readiness",
    question_text: "Have AI standards been formally adopted (ISO, IEEE, or national equivalents)?",
    option_a: "No adopted standards",
    option_b: "Standards under consideration",
    option_c: "Some standards adopted for public procurement",
    option_d: "Comprehensive standards adoption with certification programmes",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 65,
    score_d: 95,
    score_e: null
  },
  // DIMENSION 4 — DATA SOVEREIGNTY
  {
    id: 18,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "Does your nation have enforceable data residency requirements for strategic and citizen data?",
    option_a: "No data localisation requirements",
    option_b: "Data localisation laws exist but enforcement is limited",
    option_c: "Data localisation with enforcement for strategic/government data",
    option_d: "Comprehensive data residency framework with enforcement across public and private sectors",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 19,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "What proportion of government cloud workloads run on sovereign or sovereignty-graded infrastructure?",
    option_a: "Most government cloud workloads on commercial foreign cloud",
    option_b: "Some workloads on sovereign-graded cloud but majority on foreign",
    option_c: "Majority of government cloud on sovereign/domestic infrastructure",
    option_d: "All sensitive government workloads on sovereign cloud with air-gap capability",
    option_e: null,
    score_a: 15,
    score_b: 40,
    score_c: 70,
    score_d: 95,
    score_e: null
  },
  {
    id: 20,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "How does your nation govern cross-border data transfers?",
    option_a: "No specific cross-border data transfer regulations",
    option_b: "GDPR adequacy or bilateral agreement framework in place",
    option_c: "Active cross-border data flow controls with enforcement for government data",
    option_d: "Comprehensive framework: adequacy decisions, contractual clauses, and technical controls",
    option_e: null,
    score_a: 10,
    score_b: 40,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 21,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "Does your nation have classified or air-gapped computing environments for strategic AI workloads?",
    option_a: "No classified or air-gapped AI environments exist",
    option_b: "Classified environments exist but not configured for AI workloads",
    option_c: "Classified AI-ready environments with sovereign cloud regions",
    option_d: "Full trusted operating environment with jurisdictional guarantees and AI integration",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 22,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "How mature is your government's data governance capability?",
    option_a: "No formal data catalogue or quality management across government",
    option_b: "Some departments have data governance; no whole-of-government framework",
    option_c: "Whole-of-government data strategy with cataloguing and access controls",
    option_d: "Mature data governance: real-time cataloguing, quality management, stewardship roles",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 23,
    dimension: 4,
    dimension_name: "Data Sovereignty",
    question_text: "Are AI models deployed in your country trained on or fine-tuned with domestically controlled data?",
    option_a: "Models are primarily pre-trained foreign models with no domestic fine-tuning",
    option_b: "Some domestic fine-tuning but training data largely foreign-sourced",
    option_c: "Significant domestic training data under sovereign control for key use cases",
    option_d: "Sovereign AI training pipeline: domestic data collection, curation, and model training",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 95,
    score_e: null
  },
  // DIMENSION 5 — DIRECTED INTELLIGENCE MATURITY
  {
    id: 24,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "To what extent are national AI deployments tied to explicit sovereign priorities?",
    option_a: "AI deployments are opportunistic with no link to national strategy",
    option_b: "Some AI projects reference national priorities but most are ad hoc",
    option_c: "AI deployments are systematically mapped to sovereign priority areas",
    option_d: "Mission-first AI: sovereign priorities drive technology selection, not the reverse",
    option_e: null,
    score_a: 10,
    score_b: 35,
    score_c: 65,
    score_d: 90,
    score_e: null
  },
  {
    id: 25,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "What percentage of your national AI initiatives have progressed beyond pilot stage to production deployment?",
    option_a: "< 5% or unknown",
    option_b: "5–15%",
    option_c: "16–30%",
    option_d: "> 30%",
    option_e: null,
    score_a: 10,
    score_b: 30,
    score_c: 60,
    score_d: 90,
    score_e: null
  },
  {
    id: 26,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "How effective is cross-departmental AI coordination in your government?",
    option_a: "No cross-departmental AI coordination exists",
    option_b: "Informal coordination (working groups, shared Slack channels)",
    option_c: "Formal coordination body with published mandate but limited authority",
    option_d: "Systematic cross-government AI coordination with shared infrastructure and budgets",
    option_e: null,
    score_a: 5,
    score_b: 30,
    score_c: 55,
    score_d: 90,
    score_e: null
  },
  {
    id: 27,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "Can you attribute specific, documented outcomes to your AI deployments?",
    option_a: "No formal outcome measurement for AI deployments",
    option_b: "Anecdotal outcomes reported but not systematically measured",
    option_c: "Some AI deployments have documented, measured outcomes",
    option_d: "Systematic outcome attribution: all production AI systems have documented, measured impact",
    option_e: null,
    score_a: 5,
    score_b: 25,
    score_c: 55,
    score_d: 90,
    score_e: null
  },
  {
    id: 28,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "Does your government have defined human-agent decision ratios and override mechanisms?",
    option_a: "No human-agent governance framework exists",
    option_b: "General AI ethics principles but no operational human-agent rules",
    option_c: "Human-agent decision policies defined for some departments",
    option_d: "Comprehensive framework: human-agent ratios, override mechanisms, and accountability per department",
    option_e: null,
    score_a: 5,
    score_b: 25,
    score_c: 55,
    score_d: 90,
    score_e: null
  },
  {
    id: 29,
    dimension: 5,
    dimension_name: "Directed Intelligence Maturity",
    question_text: "Have your AI programmes survived at least one leadership change, budget cycle, or political transition?",
    option_a: "AI programmes are too new to have faced a transition",
    option_b: "AI programmes exist but have been disrupted by leadership or budget changes",
    option_c: "Core AI programmes survived one transition with some continuity",
    option_d: "AI programmes have institutional durability: survived multiple transitions with documented continuity",
    option_e: null,
    score_a: 20,
    score_b: 30,
    score_c: 60,
    score_d: 90,
    score_e: null
  }
];

function getAllQuestions() {
  // Group questions by dimension
  const grouped = {};
  
  ALL_QUESTIONS.forEach(q => {
    if (!grouped[q.dimension]) {
      grouped[q.dimension] = {
        dimension_id: q.dimension,
        dimension_name: q.dimension_name,
        questions: []
      };
    }
    grouped[q.dimension].questions.push({
      id: q.id,
      question_text: q.question_text,
      options: [
        { label: 'a', text: q.option_a, score: q.score_a },
        { label: 'b', text: q.option_b, score: q.score_b },
        { label: 'c', text: q.option_c, score: q.score_c },
        { label: 'd', text: q.option_d, score: q.score_d },
        ...(q.option_e ? [{ label: 'e', text: q.option_e, score: q.score_e }] : [])
      ].filter(opt => opt.text !== null)
    });
  });

  return Object.values(grouped);
}

function getQuestionById(id) {
  return ALL_QUESTIONS.find(q => q.id === id);
}

module.exports = {
  getAllQuestions,
  getQuestionById,
  ALL_QUESTIONS
};
