-- Countries Seed Data
-- Run this after creating the countries table

INSERT INTO countries (name, code, flag_emoji, description) VALUES
('United Arab Emirates', 'ARE', '🇦🇪', 'Middle East'),
('United States', 'USA', '🇺🇸', 'North America'),
('United Kingdom', 'GBR', '🇬🇧', 'Europe'),
('Singapore', 'SGP', '🇸🇬', 'Asia'),
('Saudi Arabia', 'SAU', '🇸🇦', 'Middle East'),
('Qatar', 'QAT', '🇶🇦', 'Middle East'),
('Germany', 'DEU', '🇩🇪', 'Europe'),
('France', 'FRA', '🇫🇷', 'Europe'),
('Japan', 'JPN', '🇯🇵', 'Asia'),
('South Korea', 'KOR', '🇰🇷', 'Asia'),
('China', 'CHN', '🇨🇳', 'Asia'),
('India', 'IND', '🇮🇳', 'Asia'),
('Canada', 'CAN', '🇨🇦', 'North America'),
('Australia', 'AUS', '🇦🇺', 'Oceania'),
('Brazil', 'BRA', '🇧🇷', 'South America'),
('Mexico', 'MEX', '🇲🇽', 'North America'),
('Italy', 'ITA', '🇮🇹', 'Europe'),
('Spain', 'ESP', '🇪🇸', 'Europe'),
('Netherlands', 'NLD', '🇳🇱', 'Europe'),
('Switzerland', 'CHE', '🇨🇭', 'Europe'),
('Sweden', 'SWE', '🇸🇪', 'Europe'),
('Norway', 'NOR', '🇳🇴', 'Europe'),
('Denmark', 'DNK', '🇩🇰', 'Europe'),
('Finland', 'FIN', '🇫🇮', 'Europe'),
('Belgium', 'BEL', '🇧🇪', 'Europe'),
('Austria', 'AUT', '🇦🇹', 'Europe'),
('Ireland', 'IRL', '🇮🇪', 'Europe'),
('Poland', 'POL', '🇵🇱', 'Europe'),
('Czech Republic', 'CZE', '🇨🇿', 'Europe'),
('Hungary', 'HUN', '🇭🇺', 'Europe'),
('Russia', 'RUS', '🇷🇺', 'Europe'),
('Turkey', 'TUR', '🇹🇷', 'Europe/Middle East'),
('Israel', 'ISR', '🇮🇱', 'Middle East'),
('Egypt', 'EGY', '🇪🇬', 'Africa'),
('South Africa', 'ZAF', '🇿🇦', 'Africa'),
('Nigeria', 'NGA', '🇳🇬', 'Africa'),
('Kenya', 'KEN', '🇰🇪', 'Africa'),
('Indonesia', 'IDN', '🇮🇩', 'Asia'),
('Malaysia', 'MYS', '🇲🇾', 'Asia'),
('Thailand', 'THA', '🇹🇭', 'Asia'),
('Vietnam', 'VNM', '🇻🇳', 'Asia'),
('Philippines', 'PHL', '🇵🇭', 'Asia'),
('New Zealand', 'NZL', '🇳🇿', 'Oceania'),
('Argentina', 'ARG', '🇦🇷', 'South America'),
('Chile', 'CHL', '🇨🇱', 'South America'),
('Colombia', 'COL', '🇨🇴', 'South America'),
('Peru', 'PER', '🇵🇪', 'South America'),
('Pakistan', 'PAK', '🇵🇰', 'Asia'),
('Bangladesh', 'BGD', '🇧🇩', 'Asia'),
('Sri Lanka', 'LKA', '🇱🇰', 'Asia');
