-- Seed data for SAPI Tier 1 assessment questions
-- Insert all 30 questions with their scoring

INSERT INTO questions (id, dimension, dimension_name, question_text, option_a, option_b, option_c, option_d, score_a, score_b, score_c, score_d) VALUES
-- DIMENSION 1: Compute Capacity (Questions 1-5)
(1, 1, 'Compute Capacity', 'What is your nation''s current installed AI training capacity (in petaflops of FP64 equivalent)?', '< 100 petaflops or no disclosed capacity', '100–500 petaflops with published specifications', '500–2,000 petaflops, government or national lab operated', '> 2,000 petaflops, with documented utilisation rates', 10, 35, 65, 90),
(2, 1, 'Compute Capacity', 'Do you have sovereign (domestically controlled) AI training infrastructure?', 'No sovereign training capacity; rely entirely on foreign cloud', 'Some sovereign capacity, but insufficient for large models', 'Sovereign capacity adequate for national priority models', 'Extensive sovereign capacity with export controls / foreign access restrictions', 5, 30, 65, 95),
(3, 1, 'Compute Capacity', 'What is your current AI inference capacity relative to domestic demand?', 'Severe deficit: most inference runs offshore', 'Moderate deficit: intermittent capacity constraints', 'Adequate: domestic capacity meets current demand', 'Surplus: domestic capacity exceeds demand, enabling export', 10, 40, 70, 90),
(4, 1, 'Compute Capacity', 'Is your compute infrastructure integrated with national energy security planning?', 'No integration with energy planning', 'Ad hoc coordination between AI and energy ministries', 'Formal planning documents linking AI compute to energy', 'Joint AI-Energy strategic reserve with documented contingencies', 10, 35, 65, 95),
(5, 1, 'Compute Capacity', 'Do you have documented plans for sovereign AI compute expansion?', 'No documented expansion plans', 'Plans exist but lack funding or implementation roadmap', 'Funded plan with milestones within 3 years', 'Multi-year plan with budget allocation and vendor contracts', 5, 25, 60, 95),

-- DIMENSION 2: Capital Formation (Questions 6-11)
(6, 2, 'Capital Formation', 'Is there a dedicated national AI investment fund or strategic financing mechanism?', 'No dedicated AI investment mechanism', 'Ad hoc project financing only', 'Established AI fund with < $100M AUM', 'AI fund > $100M with defined mandate and governance', 5, 30, 60, 95),
(7, 2, 'Capital Formation', 'What percentage of national AI investment is domestically sourced (vs foreign capital)?', '< 25% domestic capital', '25–50% domestic capital', '51–75% domestic capital', '> 75% domestic capital or sovereign-only financing', 10, 40, 70, 95),
(8, 2, 'Capital Formation', 'Does your national pension/sovereign wealth fund have a published AI infrastructure allocation?', 'No allocation and no plans', 'Internal discussions only', 'Published strategy but no deployment yet', 'Active deployment with disclosed commitments', 5, 25, 55, 90),
(9, 2, 'Capital Formation', 'Are there tax or regulatory incentives for domestic AI infrastructure investment?', 'No incentives specific to AI infrastructure', 'General R&D tax credits, not AI-specific', 'Targeted incentives for AI compute investment', 'Comprehensive AI investment framework with multiple incentive types', 5, 30, 65, 95),
(10, 2, 'Capital Formation', 'Do public-private AI investment partnerships exist with formal governance?', 'No formal partnerships', 'Informal collaboration only', 'Formal partnerships with limited scale', 'Multiple partnerships with disclosed governance and capital commitments', 5, 30, 60, 95),
(11, 2, 'Capital Formation', 'Is there a national AI procurement budget with multi-year certainty?', 'No specific AI procurement budget', 'Annual budget only, subject to yearly renewal', '2-year budget horizon with approved funding', 'Multi-year budget (3+ years) with parliamentary/executive approval', 5, 30, 65, 95),

-- DIMENSION 3: Regulatory Readiness (Questions 12-17)
(12, 3, 'Regulatory Readiness', 'Is there a national AI governance framework with legal force?', 'No AI-specific governance framework', 'Draft framework or voluntary guidelines only', 'Enacted legislation covering some AI applications', 'Comprehensive AI statute with regulator and enforcement powers', 5, 25, 60, 95),
(13, 3, 'Regulatory Readiness', 'Has your nation designated a lead AI regulator or oversight body?', 'No designated body', 'Working group or informal coordination', 'Designated lead agency with partial mandate', 'Dedicated AI regulator with full licensing and enforcement powers', 5, 30, 60, 95),
(14, 3, 'Regulatory Readiness', 'Do you have sector-specific AI regulations (finance, health, defence, transport)?', 'No sector-specific requirements', '1 sector with AI-specific rules', '2–3 sectors with tailored regulations', 'All critical sectors covered with tailored AI regimes', 5, 35, 65, 95),
(15, 3, 'Regulatory Readiness', 'Are AI risk classifications (e.g., prohibited, high-risk, limited-risk) defined in law?', 'No risk classification system', 'Informal or draft classification only', 'Published classification but not yet legally binding', 'Legally binding risk tiers with compliance obligations', 5, 30, 60, 95),
(16, 3, 'Regulatory Readiness', 'Does your AI framework include mandatory incident reporting for high-risk systems?', 'No incident reporting requirement', 'Voluntary reporting only', 'Mandatory reporting for public sector AI only', 'Mandatory reporting for all high-risk AI, public and private', 5, 30, 60, 95),
(17, 3, 'Regulatory Readiness', 'Have AI standards been formally adopted (ISO, IEEE, or national equivalents)?', 'No adopted standards', 'Standards under consideration', 'Some standards adopted for public procurement', 'Comprehensive standards adoption with certification programmes', 5, 30, 65, 95),

-- DIMENSION 4: Data Sovereignty (Questions 18-23)
(18, 4, 'Data Sovereignty', 'Does your nation have enforceable data residency requirements for strategic and citizen data?', 'No data localisation requirements', 'Data localisation laws exist but enforcement is limited', 'Data localisation with enforcement for strategic/government data', 'Comprehensive data residency framework with enforcement across public and private sectors', 10, 35, 65, 90),
(19, 4, 'Data Sovereignty', 'What proportion of government cloud workloads run on sovereign or sovereignty-graded infrastructure?', 'Most government cloud workloads on commercial foreign cloud', 'Some workloads on sovereign-graded cloud but majority on foreign', 'Majority of government cloud on sovereign/domestic infrastructure', 'All sensitive government workloads on sovereign cloud with air-gap capability', 15, 40, 70, 95),
(20, 4, 'Data Sovereignty', 'How does your nation govern cross-border data transfers?', 'No specific cross-border data transfer regulations', 'GDPR adequacy or bilateral agreement framework in place', 'Active cross-border data flow controls with enforcement for government data', 'Comprehensive framework: adequacy decisions, contractual clauses, and technical controls', 10, 40, 65, 90),
(21, 4, 'Data Sovereignty', 'Does your nation have classified or air-gapped computing environments for strategic AI workloads?', 'No classified or air-gapped AI environments exist', 'Classified environments exist but not configured for AI workloads', 'Classified AI-ready environments with sovereign cloud regions', 'Full trusted operating environment with jurisdictional guarantees and AI integration', 5, 30, 65, 90),
(22, 4, 'Data Sovereignty', 'How mature is your government''s data governance capability?', 'No formal data catalogue or quality management across government', 'Some departments have data governance; no whole-of-government framework', 'Whole-of-government data strategy with cataloguing and access controls', 'Mature data governance: real-time cataloguing, quality management, stewardship roles', 10, 35, 65, 90),
(23, 4, 'Data Sovereignty', 'Are AI models deployed in your country trained on or fine-tuned with domestically controlled data?', 'Models are primarily pre-trained foreign models with no domestic fine-tuning', 'Some domestic fine-tuning but training data largely foreign-sourced', 'Significant domestic training data under sovereign control for key use cases', 'Sovereign AI training pipeline: domestic data collection, curation, and model training', 10, 35, 65, 95),

-- DIMENSION 5: Directed Intelligence Maturity (Questions 24-30)
(24, 5, 'Directed Intelligence Maturity', 'To what extent are national AI deployments tied to explicit sovereign priorities?', 'AI deployments are opportunistic with no link to national strategy', 'Some AI projects reference national priorities but most are ad hoc', 'AI deployments are systematically mapped to sovereign priority areas', 'Mission-first AI: sovereign priorities drive technology selection, not the reverse', 10, 35, 65, 90),
(25, 5, 'Directed Intelligence Maturity', 'What percentage of your national AI initiatives have progressed beyond pilot stage to production deployment?', '< 5% or unknown', '5–15%', '16–30%', '> 30%', 10, 30, 60, 90),
(26, 5, 'Directed Intelligence Maturity', 'How effective is cross-departmental AI coordination in your government?', 'No cross-departmental AI coordination exists', 'Informal coordination (working groups, shared Slack channels)', 'Formal coordination body with published mandate but limited authority', 'Systematic cross-government AI coordination with shared infrastructure and budgets', 5, 30, 55, 90),
(27, 5, 'Directed Intelligence Maturity', 'Can you attribute specific, documented outcomes to your AI deployments?', 'No formal outcome measurement for AI deployments', 'Anecdotal outcomes reported but not systematically measured', 'Some AI deployments have documented, measured outcomes', 'Systematic outcome attribution: all production AI systems have documented, measured impact', 5, 25, 55, 90),
(28, 5, 'Directed Intelligence Maturity', 'Does your government have defined human-agent decision ratios and override mechanisms?', 'No human-agent governance framework exists', 'General AI ethics principles but no operational human-agent rules', 'Human-agent decision policies defined for some departments', 'Comprehensive framework: human-agent ratios, override mechanisms, and accountability per department', 5, 25, 55, 90),
(29, 5, 'Directed Intelligence Maturity', 'Have your AI programmes survived at least one leadership change, budget cycle, or political transition?', 'AI programmes are too new to have faced a transition', 'AI programmes exist but have been disrupted by leadership or budget changes', 'Core AI programmes survived one transition with some continuity', 'AI programmes have institutional durability: survived multiple transitions with documented continuity', 20, 30, 60, 90);

-- Update sequence to continue after seed data
SELECT setval('questions_id_seq', 30, true);
