-- Seed data for SAPI Tier 1 assessment questions
-- Insert all 30 questions with their scoring

INSERT INTO sapi.questions (id, dimension, dimension_name, question_text, option_a, option_b, option_c, option_d, option_e, score_a, score_b, score_c, score_d, score_e) VALUES
-- DIMENSION 1: Compute Capacity (Questions 1-5)
(1, 1, 'Compute Capacity', 'What is your organisation''s primary AI compute infrastructure?', 'We use public cloud (AWS, Azure, GCP) for all AI workloads', 'We use a mix of public cloud and on-premise GPU/TPU hardware', 'We operate dedicated on-premise AI compute (GPU clusters, HPC)', 'We operate sovereign/air-gapped compute for classified or regulated workloads', 'We have no dedicated AI compute infrastructure', 25, 50, 75, 95, 5),
(2, 1, 'Compute Capacity', 'What percentage of your AI workloads run on infrastructure located within your nation''s borders?', '0–20%', '21–50%', '51–80%', '81–100%', null, 15, 40, 70, 95, null),
(3, 1, 'Compute Capacity', 'How resilient is your AI compute to energy disruption?', 'No dedicated energy planning for AI workloads', 'Standard commercial energy contracts; no AI-specific provision', 'Dedicated energy supply agreements for data centre / AI operations', 'National grid allocation or renewable energy contracts dedicated to AI', null, 10, 35, 65, 90, null),
(4, 1, 'Compute Capacity', 'How exposed is your AI hardware supply chain to foreign dependency?', '100% dependent on foreign-fabricated chips (no domestic supply chain visibility)', 'Foreign-fabricated but with diversified suppliers and strategic stockpiles', 'Some domestic assembly or packaging; fabrication remains foreign', 'Partial domestic fabrication capability or strategic alliance with fabricator', 'Sovereign fabrication or guaranteed allied-nation supply agreement', 10, 30, 50, 75, 95),
(5, 1, 'Compute Capacity', 'What is your total installed data centre capacity dedicated to or available for AI workloads?', 'No dedicated data centre capacity', '< 10 MW total capacity', '10–50 MW', '50–200 MW', '> 200 MW', 5, 25, 50, 75, 95),

-- DIMENSION 2: Capital Formation (Questions 6-11)
(6, 2, 'Capital Formation', 'What proportion of your government''s total R&D budget is allocated to AI infrastructure and development?', 'No dedicated AI budget line', '< 1% of total R&D spend', '1–3% of total R&D spend', '3–5% of total R&D spend', '> 5% of total R&D spend', 5, 20, 45, 70, 95),
(7, 2, 'Capital Formation', 'Does your nation have sovereign wealth fund or state-backed investment vehicles with explicit AI infrastructure mandates?', 'No SWF or state-backed AI fund exists', 'SWF exists but with no AI-specific allocation', 'SWF exists with general technology allocation that includes AI', 'SWF has an explicit, published AI infrastructure allocation', null, 5, 25, 55, 90, null),
(8, 2, 'Capital Formation', 'How would you characterise the AI venture capital ecosystem in your country?', 'Minimal AI VC activity', 'Some AI VC deals but fragmented and below $500M total annually', 'Active AI VC ecosystem with $500M–$5B annually', 'Deep AI VC market with > $5B annually and domestic institutional LPs', null, 10, 35, 65, 95, null),
(9, 2, 'Capital Formation', 'Do your national development finance institutions (DFIs) have AI infrastructure financing capability?', 'No DFI involvement in AI financing', 'DFI finances general technology but not AI-specific infrastructure', 'DFI has financed AI-adjacent infrastructure in the past 3 years', 'DFI has a published AI infrastructure mandate with active pipeline', null, 5, 30, 60, 90, null),
(10, 2, 'Capital Formation', 'What is the typical timeframe from government AI budget commitment to operational infrastructure delivery?', '> 36 months or unknown', '24–36 months', '12–24 months', '< 12 months', null, 15, 40, 70, 95, null),
(11, 2, 'Capital Formation', 'Does your government have committed multi-year (5–10 year) AI infrastructure funding beyond annual budget cycles?', 'No multi-year AI funding commitment exists', 'Multi-year commitment exists in strategy documents but no legislative backing', 'Legislative or cabinet-level commitment to 3–5 year AI funding', '5–10 year committed AI infrastructure funding with legislative backing', null, 10, 35, 60, 95, null),

-- DIMENSION 3: Regulatory Readiness (Questions 12-17)
(12, 3, 'Regulatory Readiness', 'Is there a national AI governance framework with legal force?', 'No AI-specific governance framework', 'Draft framework or voluntary guidelines only', 'Enacted legislation covering some AI applications', 'Comprehensive AI statute with regulator and enforcement powers', 5, 25, 60, 95),
(13, 3, 'Regulatory Readiness', 'Has your nation designated a lead AI regulator or oversight body?', 'No designated body', 'Working group or informal coordination', 'Designated lead agency with partial mandate', 'Dedicated AI regulator with full licensing and enforcement powers', 5, 30, 60, 95),
(14, 3, 'Regulatory Readiness', 'Do you have sector-specific AI regulations (finance, health, defence, transport)?', 'No sector-specific requirements', '1 sector with AI-specific rules', '2–3 sectors with tailored regulations', 'All critical sectors covered with tailored AI regimes', 5, 35, 65, 95),
(15, 3, 'Regulatory Readiness', 'Are AI risk classifications (e.g., prohibited, high-risk, limited-risk) defined in law?', 'No risk classification system', 'Informal or draft classification only', 'Published classification but not yet legally binding', 'Legally binding risk tiers with compliance obligations', 5, 30, 60, 95),
(16, 3, 'Regulatory Readiness', 'Does your AI framework include mandatory incident reporting for high-risk systems?', 'No incident reporting requirement', 'Voluntary reporting only', 'Mandatory reporting for public sector AI only', 'Mandatory reporting for all high-risk AI, public and private', 5, 30, 60, 95),
(17, 3, 'Regulatory Readiness', 'Have AI standards been formally adopted (ISO, IEEE, or national equivalents)?', 'No adopted standards', 'Standards under consideration', 'Some standards adopted for public procurement', 'Comprehensive standards adoption with certification programmes', 5, 30, 65, 95),

-- DIMENSION 4: Data Sovereignty (Questions 18-23)
(18, 4, 'Data Sovereignty', 'Does your nation have enforceable data residency requirements for strategic and citizen data?', 'No data localisation requirements', 'Data localisation laws exist but enforcement is limited', 'Data localisation with enforcement for strategic/government data', 'Comprehensive data residency framework with enforcement across public and private sectors', 10, 35, 65, 90),
(19, 4, 'Data Sovereignty', 'What proportion of government cloud workloads run on sovereign or sovereignty-graded infrastructure?', 'Most government cloud workloads on commercial foreign cloud', 'Some workloads on sovereign-graded cloud but majority on foreign', 'Majority of government cloud on sovereign/domestic infrastructure', 'All sensitive government workloads on sovereign cloud with air-gap capability', 15, 40, 70, 95),
(20, 4, 'Data Sovereignty', 'How does your nation govern cross-border data transfers?', 'No specific cross-border data transfer regulations', 'GDPR adequacy or bilateral agreement framework in place', 'Active cross-border data flow controls with enforcement for government data', 'Comprehensive framework: adequacy decisions, contractual clauses, and technical controls', 10, 40, 65, 90),
(21, 4, 'Data Sovereignty', 'Does your nation have classified or air-gapped computing environments for strategic AI workloads?', 'No classified or air-gapped AI environments exist', 'Classified environments exist but not configured for AI workloads', 'Classified AI-ready environments with sovereign cloud regions', 'Full trusted operating environment with jurisdictional guarantees and AI integration', 5, 30, 65, 90),
(22, 4, 'Data Sovereignty', 'How mature is your government''s data governance capability?', 'No formal data catalogue or quality management across government', 'Some departments have data governance; no whole-of-government framework', 'Whole-of-government data strategy with cataloguing and access controls', 'Mature data governance: real-time cataloguing, quality management, stewardship roles', 10, 35, 65, 90),
(23, 4, 'Data Sovereignty', 'Are AI models deployed in your country trained on or fine-tuned with domestically controlled data?', 'Models are primarily pre-trained foreign models with no domestic fine-tuning', 'Some domestic fine-tuning but training data largely foreign-sourced', 'Significant domestic training data under sovereign control for key use cases', 'Sovereign AI training pipeline: domestic data collection, curation, and model training', 10, 35, 65, 95),

-- DIMENSION 5: Directed Intelligence Maturity (Questions 24-30)
(24, 5, 'Directed Intelligence Maturity', 'To what extent are national AI deployments tied to explicit sovereign priorities?', 'AI deployments are opportunistic with no link to national strategy', 'Some AI projects reference national priorities but most are ad hoc', 'AI deployments are systematically mapped to sovereign priority areas', 'Mission-first AI: sovereign priorities drive technology selection, not the reverse', 10, 35, 65, 90),
(25, 5, 'Directed Intelligence Maturity', 'What percentage of your national AI initiatives have progressed beyond pilot stage to production deployment?', '< 5% or unknown', '5–15%', '16–30%', '> 30%', 10, 30, 60, 90),
(26, 5, 'Directed Intelligence Maturity', 'How effective is cross-departmental AI coordination in your government?', 'No cross-departmental AI coordination exists', 'Informal coordination (working groups, shared Slack channels)', 'Formal coordination body with published mandate but limited authority', 'Systematic cross-government AI coordination with shared infrastructure and budgets', 5, 30, 55, 90),
(27, 5, 'Directed Intelligence Maturity', 'Can you attribute specific, documented outcomes to your AI deployments?', 'No formal outcome measurement for AI deployments', 'Anecdotal outcomes reported but not systematically measured', 'Some AI deployments have documented, measured outcomes', 'Systematic outcome attribution: all production AI systems have documented, measured impact', 5, 25, 55, 90),
(28, 5, 'Directed Intelligence Maturity', 'Does your government have defined human-agent decision ratios and override mechanisms?', 'No human-agent governance framework exists', 'General AI ethics principles but no operational human-agent rules', 'Human-agent decision policies defined for some departments', 'Comprehensive framework: human-agent ratios, override mechanisms, and accountability per department', 5, 25, 55, 90),
(29, 5, 'Directed Intelligence Maturity', 'Have your AI programmes survived at least one leadership change, budget cycle, or political transition?', 'AI programmes are too new to have faced a transition', 'AI programmes exist but have been disrupted by leadership or budget changes', 'Core AI programmes survived one transition with some continuity', 'AI programmes have institutional durability: survived multiple transitions with documented continuity', 20, 30, 60, 90),
(30, 5, 'Directed Intelligence Maturity', 'Does your nation have a sovereign AI model development programme with published roadmaps and verifiable milestones?', 'No sovereign AI model development programme exists', 'Initial discussions or exploratory studies only', 'Programme exists but lacks funding or clear milestones', 'Fully funded sovereign AI model programme with published roadmap and verifiable milestones', 10, 30, 60, 95);

-- Update sequence to continue after seed data
SELECT setval('questions_id_seq', 30, true);
